app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post_comments:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio_project:
    path:       /portfolio/{shortname}
    defaults:   { _controller: AppBundle:Project:display }

resume:
    path:       /resume
    defaults:   { _controller: AppBundle:Resume:display }
