app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post_comments:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

home:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio_project:
    path:       /portfolio/{id}
    defaults:   { _controller: AppBundle:Project:display }

resume:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }
