app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

home:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

project_daveleach:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

resume:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }
