app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

admin:
    path:       /admin
    defaults:   { _controller: AppBundle:Admin:display }

blog:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

blog_post_comments:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

fos_user:
    resource:   "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path:       /logout

message:
    path:       /message
    defaults:   { _controller: AppBundle:Message:display }

portfolio:
    path:       /
    defaults:   { _controller: AppBundle:Home:display }

portfolio_project:
    path:       /portfolio/{shortname}
    defaults:   { _controller: AppBundle:Project:display }

resume:
    path:       /resume
    defaults:   { _controller: AppBundle:Resume:display }
