security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            logout: ~
            form_login:
                login_path: /login
                check_path: /login_check

    access_control:
        # URLs that start with "admin" require the administrator role
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: ['ROLE_ADMIN'] }

    encoders:
        # PASSWORDS ARE NOT ENCODED ###########################################
        Symfony\Component\Security\Core\User\User: plaintext
