AppBundle\Entity\Accomplishment:
    type: entity
    table: ACCOMPLISHMENTS
    id:
        id:
            column: ACCO_ID
            type: integer
            unsigned: true
            generator:
                strategy: AUTO
    fields:
        description:
            column: ACCO_DESCRIPTION
            type: text
    manyToOne:
        job:
            targetEntity: Job
            joinColumn:
                name: JOB_ID
                referencedColumnName: JOB_ID
