AppBundle\Entity\Job:
    type: entity
    table: JOBS
    id:
        id:
            column: JOB_ID
            type: integer
            generator:
                strategy: AUTO
    fields:
        company:
            column: JOB_COMPANY
            type: string
            length: 50
        startdate:
            column: JOB_START
            type: date
            nullable: true
            default: null
        enddate:
            column: JOB_END
            type: date
            nullable: true
            default: null
        title:
            column: JOB_TITLE
            type: string
            length : 50
            nullable: true
