AppBundle\Entity\Project:
    type: entity
    table: PROJECTS
    id:
        id:
            column: PROJ_ID
            type: integer
            generator:
                strategy: AUTO
    fields:
        shortname:
            column: PROJ_SHORT_NAME
            type: string
            length: 20
            unique: true
        name:
            column: PROJ_NAME
            type: string
            length: 100
        description:
            column: PROJ_DESCRIPTION
            type: text
    manyToMany:
        technologies:
            targetEntity: Technology
            joinTable:
                name: PROJECT_TECHNOLOGIES
                joinColumns:
                    PROJ_ID:
                        referencedColumnName: PROJ_ID
                inverseJoinColumns:
                    TECH_ID:
                        referencedColumnName: TECH_ID
