AppBundle\Entity\Project:
    type: entity
    table: PROJECTS
    id:
        id:
            column: PROJ_ID
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: PROJ_NAME
            type: string
            length: 100
        description:
            column: PROJ_DESCRIPTION
            type: text
        routepath:
            column: PROJ_ROUTE_PATH
            type: string
            length: 30
        routeid:
            column: PROJ_ROUTE_ID
            type: string
            length: 30
