<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIMw7jij\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIMw7jij/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIMw7jij.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIMw7jij\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIMw7jij\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IMw7jij',
    'container.build_id' => '272d4bad',
    'container.build_time' => 1533605172,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIMw7jij');
